"""U.S. health-informatics job titles — search + scoring source of truth."""

from __future__ import annotations

TARGET_TITLES_BY_CATEGORY: dict[str, list[str]] = {
    "epic_ehr": [
        "Epic Application Analyst",
        "Epic Clinical Systems Analyst I",
        "Epic Clinical Systems Analyst II",
        "Epic Inpatient Application Analyst",
        "Epic Ambulatory Application Analyst",
        "Epic Revenue Cycle Application Analyst",
        "Epic HIM (Health Information Management) Analyst",
        "Epic Resolute Analyst",
        "Epic Cogito Analyst",
        "Epic Clarity Analyst",
        "Epic Hospital Billing (HB) Analyst",
        "Epic Professional Billing (PB) Analyst",
        "Epic Cadence Analyst",
        "Epic Prelude Analyst",
        "Epic Eligibility Analyst",
        "Epic Beaker Analyst",
        "Epic Patient Access Analyst",
    ],
    "clinical_informatics": [
        "Clinical Informatics Analyst",
        "Clinical Informatics Specialist",
        "Clinical Informatics Manager",
        "Chief Clinical Information Officer (CCIO)",
        "Clinical Systems Analyst",
        "Clinical Application Analyst",
        "Senior Clinical Informatics Specialist",
        "Senior Clinical Systems Analyst",
        "Clinical Informatics Coordinator",
    ],
    "revenue_cycle_him": [
        "Revenue Cycle Analyst",
        "Revenue Cycle Epic Analyst",
        "Revenue Cycle Operations Analyst",
        "Revenue Cycle Manager",
        "HIM Analyst",
        "Health Information Manager",
        "Health Information Officer",
        "Clinical Documentation Improvement (CDI) Specialist",
        "CDI Coordinator",
        "CDI Manager",
        "Denial Management Analyst",
        "Billing Systems Analyst",
        "Patient Access Optimization Analyst",
        "Revenue Cycle Quality Analyst",
    ],
    "ehr_implementation": [
        "EHR Implementation Specialist",
        "EHR Application Support Analyst",
        "EHR Systems Analyst",
        "EHR Go-Live Support Specialist",
        "EHR Analyst",
        "Health IT Implementation Analyst",
        "Health Information Technology Implementation Specialist",
        "Implementation Analyst",
        "Application Systems Analyst II",
        "Systems Analyst II (Healthcare)",
    ],
    "it_support": [
        "Clinical Service Desk Analyst I",
        "Clinical Service Desk Analyst II",
        "IT Support Analyst",
        "IT Systems Analyst",
        "Application Support Analyst",
        "Technical Support Analyst",
        "Help Desk Technician",
        "Help Desk Team Lead",
        "IT Support Specialist",
        "IT Service Desk Analyst",
    ],
    "data_testing": [
        "Health IT Data Analyst",
        "Clinical Data Analyst",
        "Healthcare Data Specialist",
        "Healthcare Data Engineer",
        "QA Analyst (Healthcare)",
        "Test Analyst (Healthcare)",
        "Quality Assurance Analyst",
        "Quality Assurance Engineer",
        "Systems Test Analyst",
        "Integration Test Analyst",
    ],
    "project_process": [
        "Health IT Project Coordinator",
        "Healthcare IT Project Manager",
        "EHR Project Manager",
        "Health IT Project Manager",
        "Health IT Business Analyst",
        "Healthcare Business Analyst",
        "Workflow Analyst",
        "Process Improvement Analyst",
        "Business Analyst — Healthcare IT",
        "Workflow Optimization Specialist",
        "Health Systems Project Manager",
        "Clinical Workflow Consultant",
    ],
    "senior_lead": [
        "Senior Epic Application Analyst",
        "Senior Clinical Systems Analyst",
        "Lead Clinical Systems Analyst",
        "Senior Health IT Analyst",
        "Senior Clinical Informatics Analyst",
        "Senior Revenue Cycle Analyst",
        "Lead Health IT Analyst",
        "Senior Application Analyst",
        "Applications Analyst II",
        "Systems Analyst III",
    ],
    "specialized_healthcare_it": [
        "Clinical Informatics Consultant",
        "Health IT Consultant",
        "Healthcare IT Specialist",
        "Digital Health Analyst",
        "Health Information Systems Analyst",
        "Clinical Systems Support Specialist",
        "Hospital Information Systems Analyst",
        "Medical Records Information Specialist",
        "Healthcare IT Coordinator",
        "Clinical Application Specialist",
        "Clinical Support Analyst",
        "Hospital Systems Specialist",
        "Clinical IT Coordinator",
    ],
    "interoperability": [
        "FHIR Integration Analyst",
        "HL7 Interface Analyst",
        "Health Data Interoperability Specialist",
        "Clinical Data Integration Specialist",
        "Healthcare Integration Engineer",
        "Health Data Integration Specialist",
        "Epic Interface Analyst",
        "Interface Development Analyst",
        "HL7 Interface Developer",
    ],
    "training_change": [
        "Health IT Trainer",
        "Clinical Systems Trainer",
        "EHR Super User",
        "EHR Key User",
        "Change Management Coordinator (Healthcare IT)",
        "Clinical Workflow Change Manager",
        "Health IT Documentation Specialist",
        "Clinical Training Specialist",
        "Training Coordinator (Healthcare IT)",
        "Change Management Specialist",
    ],
    "hybrid_clinical_it": [
        "Clinical IT Specialist",
        "Clinical Operations Analyst",
        "Healthcare Operations Analyst",
        "Clinical Workflow Specialist",
        "Patient Safety Informatics Specialist",
    ],
    "management": [
        "Health Informatics Manager",
        "EHR Manager",
        "EHR Program Manager",
        "Health IT Manager",
        "HIM Manager",
        "Clinical Systems Manager",
        "IT Operations Manager (Healthcare)",
        "Information Services Manager",
        "Department Manager (Healthcare IT)",
        "Epic Program Manager",
        "Clinical Technology Manager",
    ],
    "director_leadership": [
        "Director of Clinical Informatics",
        "Director of Health Informatics",
        "Director of HIM",
        "Director of Health IT",
        "Chief Information Officer — Clinical Systems",
        "Health IT Director",
        "Information Services Director",
        "Clinical Systems Director",
        "Vice President of Clinical Informatics",
        "Vice President of Health IT",
    ],
    "consulting_vendor": [
        "Healthcare IT Consultant",
        "Healthcare Systems Consultant",
        "Epic Implementation Consultant",
        "EHR Consultant",
        "Health Information Systems Consultant",
        "Healthcare Technology Consultant",
        "Solutions Consultant (Healthcare)",
        "Solutions Architect (Healthcare)",
        "Implementation Manager",
        "Account Manager (Healthcare IT)",
        "Technical Account Manager (Healthcare)",
    ],
    "federal_government": [
        "Federal Health IT Analyst",
        "Health IT Informatics Analyst",
        "Real-World Data & Clinical Informatics Data Engineer",
        "VA Health IT Analyst",
        "CMS Health IT Specialist",
        "CDC Health Informatics Specialist",
        "Health Informatics Officer",
        "Government Health IT Consultant",
    ],
    "academic_research": [
        "Health Informatics Researcher",
        "Clinical Informatics Research Specialist",
        "Healthcare Systems Research Analyst",
        "Health Data Analyst (Research)",
        "Bioinformatics Specialist (Healthcare)",
    ],
    "additional": [
        "Epic Trainer",
        "Technical Solutions Engineer",
        "Project Manager (Epic)",
        "Quality Manager (Healthcare)",
        "Systems Engineer II (Epic)",
        "Data Engineer IV (Healthcare)",
        "Real-World Data Analyst",
        "Patient Access System Analyst",
        "System Business Office Analyst",
        "Application System Analyst",
        "IT Analyst I",
        "IT Analyst II",
        "Clinical Application Systems Analyst",
        "Enterprise Systems Analyst",
        "Healthcare Systems Engineer",
    ],
}

TARGET_TITLES_BY_STATE: dict[str, list[str]] = {
    "texas": [
        "Epic Clinical Systems Analyst I",
        "Revenue Cycle Epic Builders Analyst",
        "Epic HIM Analyst",
        "Clinical Informatics Analyst",
        "EHR Implementation Specialist",
        "Clinical Systems Analyst",
        "Healthcare IT Analyst",
        "Health IT Project Manager",
        "Health Data Analyst",
        "Revenue Cycle Operations Analyst",
    ],
    "north_carolina": [
        "Applications Analyst - Epic Inpatient",
        "Clinical Systems Analyst I",
        "Healthcare IT Analyst",
        "Epic Application Analyst",
        "Clinical Informatics Specialist",
        "EHR Implementation Specialist",
        "Health IT Project Manager",
        "Systems Analyst (Healthcare)",
    ],
    "nj_ny_pa": [
        "Application Analyst I",
        "Clinical Systems Analyst",
        "Healthcare IT Analyst",
        "Epic Application Analyst",
        "Senior Clinical Systems Analyst",
        "Health IT Project Manager",
        "Data Engineer",
        "Clinical Informatics Analyst",
        "Healthcare Project Manager",
        "Systems Engineer (Epic)",
    ],
}

ALL_TARGET_TITLES: list[str] = []
_seen: set[str] = set()
for _titles in list(TARGET_TITLES_BY_CATEGORY.values()) + list(TARGET_TITLES_BY_STATE.values()):
    for t in _titles:
        key = t.lower().strip()
        if key not in _seen:
            _seen.add(key)
            ALL_TARGET_TITLES.append(t)

# API / ATS search terms for employer career page adapters
SEARCH_QUERIES: list[str] = [
    # Epic / EHR modules
    "Epic", "Epic analyst", "Epic application", "clinical systems analyst",
    "Epic inpatient", "Epic ambulatory", "Epic revenue cycle", "Epic HIM",
    "Epic Resolute", "Epic Cogito", "Epic Clarity", "Epic Cadence",
    "Epic Prelude", "Epic Beaker", "Epic patient access", "Epic HB", "Epic PB",
    # Clinical informatics
    "clinical informatics", "informatics analyst", "informatics specialist",
    "clinical application analyst", "CCIO",
    # HIM / CDI / revenue cycle
    "health information", "HIM analyst", "HIM manager", "medical records",
    "CDI", "clinical documentation", "revenue cycle", "revenue integrity",
    "denial management", "billing systems", "patient access",
    # Implementation & support
    "EHR implementation", "EHR analyst", "EHR support", "go-live",
    "application support", "clinical service desk", "help desk",
    # Data / QA / testing
    "health data analyst", "clinical data analyst", "healthcare data",
    "QA analyst healthcare", "test analyst", "quality assurance",
    # Project / business / workflow
    "health IT project", "healthcare IT project manager", "EHR project manager",
    "health IT business analyst", "workflow analyst", "process improvement",
    # Interoperability
    "FHIR", "HL7", "interface analyst", "integration analyst", "interoperability",
    # Training / change
    "Epic trainer", "clinical systems trainer", "change management healthcare",
    # Senior / lead
    "senior epic", "senior clinical systems", "lead health IT",
    # Consulting / vendor
    "healthcare IT consultant", "Epic implementation consultant",
    # Federal / research
    "VA health IT", "CMS health IT", "health informatics officer",
    # General health IT
    "health IT", "healthcare IT", "digital health", "health informatics",
    "hospital information systems", "clinical systems", "application analyst",
    "systems analyst healthcare", "health information systems",
]
